automation-test/src/test/resources/application-aat.properties

Test branch for aat deployment and functional test

empty commit

---

automation-test/src/test/resources/application-aat.properties

Fix automated test and docker

---

automation-test/.gitignore
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/client/DefaultTransformationHttpEntityFactory.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/client/TransformationHttpEntityFactory.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/client/pdf/PdfGeneratorClient.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/client/pdf/PdfGeneratorDefaultClient.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallBackController.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/service/PdfGeneratorService.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/service/PdfService.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/service/UpdateService.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/client/pdf/PdfGeneratorDefaultClientTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/functional/CaseAddPdfFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/service/PdfGeneratorServiceTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/service/UpdateServiceTest.java

Add jwt token to div doc gen

---

.gitignore
docker-compose.yml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/mapping/DocumentCollectionMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/mapping/DocumentUrlRewrite.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/mapping/DocumentCollectionMapperTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/mapping/DocumentUrlRewriteTest.java
src/test/resources/application.properties

Change the document url if the document does not come from DM deployed on CNP

Rewrite document url if it doesn't come from cnp

---

build.gradle
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/functional/CaseAddPdfFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/functional/CaseSubmissionFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/functional/CaseUpdateFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/functional/HealthCheckFunctionalTest.java

Updated wiremock to spring-cloud-contract-wiremock

Updated to Spring cloud wiremock

---

src/main/java/uk/gov/hmcts/reform/divorce/draftservice/service/AwaitingPaymentCaseRetriever.java
src/main/java/uk/gov/hmcts/reform/divorce/draftservice/service/DraftsService.java
src/test/java/uk/gov/hmcts/reform/divorce/draftservice/service/DraftsServiceTest.java

Reverts hmcts/div-case-progression-service #49 until we have can merge the changes to retrieve the case from CCD

Revert "DIV-2661: Change how save and close works after CYA"

---

src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java

Fixed checkstyle issues in test

---

.gitignore
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
src/main/java/uk/gov/hmcts/reform/divorce/notifications/domain/EmailTemplateNames.java
src/main/java/uk/gov/hmcts/reform/divorce/notifications/service/EmailService.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallBackController.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/divorce/notifications/service/EmailServiceTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java
src/test/resources/application.properties

Richard's submit email changes with some additional test coverage and caseId fix.

Clean submit email notification branch

---

build.gradle

https://tools.hmcts.net/jira/browse/DIV-2830
Added mutation testing for CPS.
* Hardware:
* JDK:

DIV-2830 Add mutation testing: Added configs for mutation testing CPS

---

dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallBackController.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java

Added formatting of case reference id prior to applying it to the email template
DIV-2847
- [x ] Bug fix (non-breaking change which fixes an issue)
unit tests
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes

Div-2847 submitted email   minor formatting and text changes

---

src/main/java/uk/gov/hmcts/reform/divorce/transformservice/domain/model/ccd/CoreCaseData.java
src/test/resources/divorce-payload-json/add-pdf-response-with-errors.json
src/test/resources/divorce-payload-json/add-pdf-response-with-warnings.json
src/test/resources/divorce-payload-json/add-pdf-response.json
src/test/resources/fixtures/pdf-generator/generate-pdf-request.json
src/test/resources/fixtures/validation-service/validate-request-no-documenttype.json
src/test/resources/fixtures/validation-service/validate-request.json

Added a field to the CCD model

Add DerivedPetitionerSolicitorAddr to the CoreCaseData model

---

src/main/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallBackController.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/domain/model/ccd/CoreCaseData.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java
src/test/resources/divorce-payload-json/add-pdf-no-documenttype.json
src/test/resources/divorce-payload-json/add-pdf-response-with-errors.json
src/test/resources/divorce-payload-json/add-pdf-response-with-warnings.json
src/test/resources/divorce-payload-json/add-pdf-response.json
src/test/resources/fixtures/pdf-generator/generate-pdf-request.json
src/test/resources/fixtures/validation-service/validate-request-no-documenttype.json
src/test/resources/fixtures/validation-service/validate-request.json

ignore pba payments

---

src/main/java/uk/gov/hmcts/reform/divorce/errorhandler/CcdCallbackExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/divorce/fees/services/FeesAndPaymentService.java
src/main/java/uk/gov/hmcts/reform/divorce/pay/exceptions/FeesNotFoundException.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java

throw exception, if cannot retrieve fees

---

src/main/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallBackController.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/domain/model/ccd/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/domain/model/ccd/OrderSummary.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallbackControllerTest.java
src/test/resources/divorce-payload-json/add-pdf-no-documenttype.json
src/test/resources/divorce-payload-json/add-pdf-response-with-errors.json
src/test/resources/divorce-payload-json/add-pdf-response-with-warnings.json
src/test/resources/divorce-payload-json/add-pdf-response.json
src/test/resources/fixtures/pdf-generator/generate-pdf-request.json
src/test/resources/fixtures/validation-service/validate-request-no-documenttype.json
src/test/resources/fixtures/validation-service/validate-request.json

added sol and petitioner statement of truth check

---

src/main/java/uk/gov/hmcts/reform/divorce/errorhandler/CcdCallbackExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/controller/CcdCallBackController.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/domain/model/ccd/CoreCaseData.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/functional/HealthCheckFunctionalTest.java
src/test/resources/divorce-payload-json/add-pdf-no-documenttype.json
src/test/resources/divorce-payload-json/add-pdf-response-with-errors.json
src/test/resources/divorce-payload-json/add-pdf-response-with-warnings.json
src/test/resources/divorce-payload-json/add-pdf-response.json
src/test/resources/fixtures/pdf-generator/generate-pdf-request.json
src/test/resources/fixtures/validation-service/validate-request-no-documenttype.json
src/test/resources/fixtures/validation-service/validate-request.json

Solicitor journey branch

---

src/main/java/uk/gov/hmcts/reform/divorce/draftservice/factory/DraftResponseFactory.java
src/main/java/uk/gov/hmcts/reform/divorce/draftservice/service/DraftsRetrievalService.java
src/main/java/uk/gov/hmcts/reform/divorce/draftservice/service/DraftsService.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/client/RetrieveCcdClient.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/service/SubmissionService.java
src/main/java/uk/gov/hmcts/reform/divorce/transformservice/service/UpdateService.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/service/SubmissionServiceTest.java
src/test/java/uk/gov/hmcts/reform/divorce/transformservice/service/UpdateServiceTest.java

Adds the userId from retrieval from idam /details endpoint to the logs in the same code block, so its easier to search for when required.
https://tools.hmcts.net/jira/browse/DIV-3103
All existing tests pass. Local verification of logs was done.

Update existing logs with UserId or CaseId details

---

infrastructure/main.tf

[PREVIEW] Remove provider vault

---

src/main/java/uk/gov/hmcts/reform/divorce/draftservice/factory/DraftResponseFactory.java
src/main/java/uk/gov/hmcts/reform/divorce/draftservice/service/DraftsRetrievalService.java
src/test/java/uk/gov/hmcts/reform/divorce/draftservice/factory/DraftResponseFactoryTest.java
src/test/java/uk/gov/hmcts/reform/divorce/draftservice/service/DraftsRetrievalServiceTest.java

This PR is the same as the changes from https://github.com/hmcts/div-case-progression-service/pull/133
It was just simpler to create a new branch rather than fix the merge conflicts
https://tools.hmcts.net/jira/browse/DIV-2663
https://tools.hmcts.net/jira/browse/DIV-2663

[PREVIEW] DIV-2663: Resume case from CCD when multiple cases found

---

automation-test/src/test/java/uk/gov/hmcts/reform/divorce/caseprogression/e2e/CaseSubmissionMiniPetitionGenerationE2ETest.java

Reverts hmcts/div-case-progression-service#148

Revert "TO BE REVERTED: Commented out actual callback tests"

---

infrastructure/main.tf
infrastructure/variables.tf

Use shared ASP on Preview
* Hardware:
* JDK:

[PREVIEW] use shared ASP
